version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "80:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:1905@localhost:5432/Insuarance_fraud
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1905
      - POSTGRES_DB=Insuarance_fraud
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
